name: Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun Runtime
        uses: oven-sh/setup-bun@v2
      - name: Setup Biome CLI
        uses: biomejs/setup-biome@v2
        with:
          version: 1.9.3
      - name: Run Biome linter and formatter
        run: bun lint-format:fix
